packages:
  - apps/*
  - packages/*

# From `@pnpm/plugin-better-defaults`
enablePrePostScripts: false
ignorePatchFailures: false
optimisticRepeatInstall: true
resolutionMode: "lowest-direct"

catalog:
  "typescript": "5.9.2"

catalogs:
  react18:
    "@types/react": "18.3.24"
    "@types/react-dom": "18.3.7"
    "react": "18.3.1"
    "react-dom": "18.3.1"
  # Rsbuild monorepo packages
  rsbuild:
    "@rsbuild/core": "1.5.4"
    "@rsbuild/plugin-react": "1.4.0"

  # Rspack monorepo packages
  rspack:
    "@rspack/cli": "1.5.2"
    "@rspack/core": "1.5.2"
    "@rspack/test-tools": "1.5.2"

overrides:
  "@rspack/core": "catalog:rspack"
  "@rsbuild/core>@rspack/core": "catalog:rspack"

strictDepBuilds: true

onlyBuiltDependencies:
  - dprint
  - esbuild

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - unrs-resolver
