packages:
  - apps/*
  - packages/*

catalog:
  rsbuild-plugin-tailwindcss: 0.2.3
  tailwindcss: 3.4.17
  tailwind-merge: 2.6.0
  typescript: 5.9.2

catalogs:
  lynx:
    "@lynx-js/types": 3.4.11
  react18:
    "@types/react": 18.3.24
    "@types/react-dom": 18.3.7
    react: 18.3.1
    react-dom: 18.3.1
  rsbuild:
    "@rsbuild/core": 1.5.4
    "@rsbuild/plugin-react": 1.4.0
  rspack:
    "@rspack/cli": 1.5.2
    "@rspack/core": 1.5.2
    "@rspack/test-tools": 1.5.2

enablePrePostScripts: false

ignorePatchFailures: false

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - unrs-resolver

onlyBuiltDependencies:
  - dprint
  - esbuild

optimisticRepeatInstall: true

overrides:
  "@rsbuild/core>@rspack/core": catalog:rspack
  "@rspack/core": catalog:rspack

resolutionMode: lowest-direct

strictDepBuilds: true
