packages:
  - apps/*
  - packages/*

catalog:
  clsx: 2.1.1
  rsbuild-plugin-tailwindcss: 0.2.3
  tailwindcss: 3.4.17
  tailwind-merge: 2.6.0
  typescript: 5.9.2
  "@types/node": 24.6.1
  "@typescript/native-preview": 7.0.0-dev.20251103.1

catalogs:
  lynx:
    "@lynx-js/qrcode-rsbuild-plugin": 0.3.3
    "@lynx-js/react": 0.114.4
    "@lynx-js/react-rsbuild-plugin": 0.11.4
    "@lynx-js/rspeedy": 0.11.8
    "@lynx-js/types": 3.4.11
    "@lynx-js/tailwind-preset": 0.4.0
  react18:
    "@types/react": 18.3.24
    "@types/react-dom": 18.3.7
    react: 18.3.1
    react-dom: 18.3.1
  rsbuild:
    "@rsbuild/core": 1.6.1
    "@rsbuild/plugin-react": 1.4.2
  rslib:
    "@rslib/core": 0.17.1

enablePrePostScripts: false

ignorePatchFailures: false

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - unrs-resolver

onlyBuiltDependencies:
  - dprint
  - esbuild

optimisticRepeatInstall: true

resolutionMode: lowest-direct

strictDepBuilds: true
